version: '3.8'

services:
  api:
    build:
      context: ./hotel-management-api
      dockerfile: Dockerfile
    volumes:
      - ./hotel-management-api:/var/www/html:rw
    working_dir: /var/www/html
    command: php artisan serve --host=0.0.0.0 --port=8000
    ports:
      - "8000:8000"
    depends_on:
      - database

  database:
    image: postgres
    environment:
      POSTGRES_DB: hotel_management
      POSTGRES_USER: hotel_admin
      POSTGRES_PASSWORD: password
    ports:
      - "54321:5432"
    volumes:
      - ./hotel-management-data/postgres:/var/lib/postgresql/data:rw